/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mergesort.h"

bool_t
xdr_merge_in (XDR *xdrs, merge_in *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->input_array, 100,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->input_array;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->size);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->input_array, 100,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->input_array;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->size = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->input_array, 100,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_merge_out (XDR *xdrs, merge_out *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->output_array, 100,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->output_array;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->size);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->output_array, 100,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->output_array;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->size = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->output_array, 100,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_deleteElm (XDR *xdrs, deleteElm *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->elm))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_position (XDR *xdrs, position *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->pos))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_key (XDR *xdrs, key *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->elm))
		 return FALSE;
	return TRUE;
}
